//
//  SemanticColor.swift
//  MDS
//
//  Auto-generated by Style Dictionary. Do not edit manually.
//

import UIKit

// MARK: - Semantic Color

public enum SemanticColor {

    public enum Bg {

        public enum Neutral {
            public static let inverse = BaseColor.gray10
            public static let bold = BaseColor.gray500
            public static let `default` = BaseColor.gray600
            public static let subtle = BaseColor.gray700
            public static let ghost = BaseColor.gray800

            public enum Inverse {
                public static let hover = BaseColor.gray100
                public static let pressed = BaseColor.gray100
            }

            public enum Bold {
                public static let disabled = BaseColor.gray700
            }

            public enum Default {
                public static let hover = BaseColor.gray500
                public static let pressed = BaseColor.gray500
                public static let disabled = BaseColor.gray800
            }

            public enum Subtle {
                public static let hover = BaseColor.gray600
                public static let pressed = BaseColor.gray600
            }

            public enum Ghost {
                public static let hover = BaseColor.gray700
                public static let pressed = BaseColor.gray700
            }
        }

        public enum Brand {
            public static let `default` = BaseColor.orange400
            public static let subtle = BaseColor.orange700
            public static let ghost = BaseColor.orange950
        }

        public enum Secondary {
            public static let `default` = BaseColor.blue400
            public static let subtle = BaseColor.blue900
            public static let ghost = BaseColor.blue950

            public enum Default {
                public static let hover = BaseColor.blue500
                public static let pressed = BaseColor.blue600
            }
        }

        public enum Information {
            public static let ghost = BaseColor.blue950
        }

        public enum Success {
            public static let ghost = BaseColor.green950
        }

        public enum Danger {
            public static let `default` = BaseColor.red400
            public static let ghost = BaseColor.red950

            public enum Default {
                public static let hover = BaseColor.red500
                public static let pressed = BaseColor.red600
            }
        }

        public enum Dim {
            public static let `default` = BaseColor.gray950.withAlphaComponent(0.8)
        }

        public enum Layer {
            public static let basement = BaseColor.gray950
            public static let `default` = BaseColor.gray900

            public enum Basement {
                public static let hover = BaseColor.gray800
            }

            public enum Default {
                public static let hover = BaseColor.gray800
            }
        }
    }

    public enum Fg {

        public enum Neutral {
            public static let bold = BaseColor.gray10
            public static let `default` = BaseColor.gray100
            public static let subtle = BaseColor.gray300
            public static let ghost = BaseColor.gray500
            public static let inverse = BaseColor.gray950

            public enum Default {
                public static let disabled = BaseColor.gray500
            }

            public enum Ghost {
                public static let disabled = BaseColor.gray700
            }
        }

        public enum Brand {
            public static let `default` = BaseColor.orange400
        }

        public enum Secondary {
            public static let `default` = BaseColor.blue400
        }

        public enum Information {
            public static let `default` = BaseColor.blue400
            public static let subtle = BaseColor.blue600
        }

        public enum Success {
            public static let bold = BaseColor.green100
            public static let `default` = BaseColor.green400
            public static let subtle = BaseColor.green600
        }

        public enum Danger {
            public static let bold = BaseColor.red100
            public static let `default` = BaseColor.red400
            public static let subtle = BaseColor.red600
        }

        public enum Attention {
            public static let bold = BaseColor.yellow200
            public static let `default` = BaseColor.yellow400
            public static let subtle = BaseColor.yellow600
        }
    }

    public enum Stroke {

        public enum Neutral {
            public static let `default` = BaseColor.gray600
            public static let inverse = BaseColor.gray10
            public static let subtle = BaseColor.gray700
            public static let ghost = BaseColor.gray800

            public enum Default {
                public static let focused = BaseColor.gray200
                public static let disabled = BaseColor.gray700
            }
        }

        public enum Brand {
            public static let `default` = BaseColor.orange400
            public static let subtle = BaseColor.orange600
        }

        public enum Secondary {
            public static let `default` = BaseColor.blue400
            public static let subtle = BaseColor.blue600
        }

        public enum Information {
            public static let subtle = BaseColor.blue600
        }

        public enum Danger {
            public static let `default` = BaseColor.red400
        }
    }
}
