import StyleDictionary from 'style-dictionary';

const capitalize = (str) => str.charAt(0).toUpperCase() + str.slice(1);

// Strips "px" or "%" units from token values and returns a plain number string.
const toNumber = (val) => parseFloat(String(val).replace('px', '').replace('%', ''));

const hexToRGB = (hex) => {
  const h = hex.replace('#', '');
  return {
    r: (parseInt(h.slice(0, 2), 16) / 255).toFixed(3),
    g: (parseInt(h.slice(2, 4), 16) / 255).toFixed(3),
    b: (parseInt(h.slice(4, 6), 16) / 255).toFixed(3),
  };
};

const fileHeader = (filename) =>
`//
//  ${filename}
//  MDS
//
//  Auto-generated by Style Dictionary. Do not edit manually.
//

import UIKit

`;

StyleDictionary.registerFormat({
  name: 'ios/swift-color-base',
  format: ({ dictionary }) => {
    let output = fileHeader('BaseColor.swift');
    output += '// MARK: - Base Color (Internal Only)\n\n';
    output += 'internal enum BaseColor {\n';

      for (const token of dictionary.allTokens) {
            const colorName = token.path[2];
            const shade = token.path[token.path.length - 1];
            const hex = token.$value ?? token.value;
            const { r, g, b } = hexToRGB(hex);

            output += `    static let ${colorName}${shade} = UIColor(red: ${r}, green: ${g}, blue: ${b}, alpha: 1)\n`;
          }

          output += '}\n';
          return output;
    }
});

StyleDictionary.registerFormat({
  name: 'ios/swift-typography',
  format: ({ dictionary }) => {
    let output = fileHeader('BaseTypography.swift');
    output += '// MARK: - Base Typography (Internal Only)\n\n';
    output += 'internal enum BaseTypography {\n';

    const groups = {};
    for (const token of dictionary.allTokens) {
      const cat = token.path[2];
      if (!groups[cat]) groups[cat] = [];
      groups[cat].push(token);
    }

    for (const [cat, tokens] of Object.entries(groups)) {
      output += `\n    // MARK: ${capitalize(cat)}\n`;
      output += `    enum ${capitalize(cat)} {\n`;
      for (const token of tokens) {
        const last = token.path[token.path.length - 1];
        let name;
        if (cat === 'size' || cat === 'lineHeight') {
          name = last;
        } else if (last === 'default') {
          name = '`default`';
        } else {
          name = last;
        }
        output += `        static let ${name}: CGFloat = ${toNumber(token.$value ?? token.value)}\n`;
      }
      output += `    }\n`;
    }

    output += '}\n';
    return output;
  }
});

StyleDictionary.registerFormat({
  name: 'ios/swift-spacing',
  format: ({ dictionary }) => {
    let output = fileHeader('BaseSpacing.swift');
    output += '// MARK: - Base Spacing (Internal Only)\n\n';
    output += 'internal enum BaseSpacing {\n';

    const groups = {};
    for (const token of dictionary.allTokens) {
      const cat = token.path[1];
      if (!groups[cat]) groups[cat] = [];
      groups[cat].push(token);
    }

    for (const [cat, tokens] of Object.entries(groups)) {
      output += `\n    // MARK: ${capitalize(cat)}\n`;
      output += `    enum ${capitalize(cat)} {\n`;
      for (const token of tokens) {
        const last = token.path[token.path.length - 1];
        output += `        static let ${last}: CGFloat = ${toNumber(token.$value ?? token.value)}\n`;
      }
      output += `    }\n`;
    }

    output += '}\n';
    return output;
  }
});

const fontNameMap = {
  '700': 'Pretendard-Bold',
  '600': 'Pretendard-SemiBold',
  '400': 'Pretendard-Regular',
};

const swiftWeightMap = {
  '700': '.bold',
  '600': '.semibold',
  '400': '.regular',
};

StyleDictionary.registerFormat({
  name: 'ios/swift-typography-semantic',
  format: ({ dictionary }) => {
    let output = fileHeader('Typography.swift');
    output += '// MARK: - Semantic Typography\n\n';
    output += 'public enum Typography {\n';

    for (const token of dictionary.allTokens) {
      const cat = token.path[1];
      const num = token.path[2];
      const name = `${cat}${num}`;
      const val = token.$value ?? token.value;

      const weightKey = String(toNumber(val.fontWeight));
      const fontSize = toNumber(val.fontSize);
      const lineHeight = toNumber(val.lineHeight);
      const letterSpacingPercent = toNumber(val.letterSpacing);
      const letterSpacing = parseFloat((fontSize * (letterSpacingPercent / 100)).toFixed(2));

      const fontName = fontNameMap[weightKey] ?? 'Pretendard-Regular';
      const swiftWeight = swiftWeightMap[weightKey] ?? '.regular';

      output += `    public static let ${name} = MDSFont(\n`;
      output += `        font: UIFont(name: "${fontName}", size: ${fontSize}) ?? .systemFont(ofSize: ${fontSize}, weight: ${swiftWeight}),\n`;
      output += `        lineHeight: ${lineHeight},\n`;
      output += `        letterSpacing: ${letterSpacing}\n`;
      output += `    )\n`;
    }

    output += '}\n';
    return output;
  }
});

const toSwiftName = (str) => {
  const camel = str.replace(/-([a-z])/g, (_, c) => c.toUpperCase());
  return camel === 'default' ? '`default`' : camel;
};

const resolveBaseColorReference = (value) => {
  if (typeof value !== 'string') return null;

    const match = value.match(/^\{color\.base\.([^.]+)\.([^.}]+)\}$/);
    if (!match) return null;
    const colorName = match[1];
    const shade = match[2];
    return `BaseColor.${colorName}${shade}`;
};

const STATE_SUFFIXES = ['hover', 'pressed', 'disabled', 'focused'];
const isStateSuffix = (str) => STATE_SUFFIXES.includes(str);

const parseTokenName = (name) => {
  const parts = name.split('-');
  const last = parts[parts.length - 1];
  if (isStateSuffix(last)) {
    return {
      base: parts.slice(0, -1).join('-'),
      state: last,
    };
  }
  return { base: name, state: null };
};

StyleDictionary.registerFormat({
  name: 'ios/swift-color-semantic',
  format: ({ dictionary }) => {
    let output = fileHeader('SemanticColor.swift');
    output += '// MARK: - Semantic Color\n\n';
    output += 'public enum SemanticColor {\n';

    const level1Groups = {};
    for (const token of dictionary.allTokens) {
      const level1 = token.path[1];
      if (!level1Groups[level1]) level1Groups[level1] = [];
      level1Groups[level1].push(token);
    }

    for (const [level1, tokens] of Object.entries(level1Groups)) {
      output += `\n    public enum ${capitalize(level1)} {\n`;

      const level2Groups = {};
      for (const token of tokens) {
        const level2 = token.path[2];
        if (!level2Groups[level2]) level2Groups[level2] = [];
        level2Groups[level2].push(token);
      }

      for (const [level2, innerTokens] of Object.entries(level2Groups)) {
        output += `\n        public enum ${capitalize(level2)} {\n`;

        // base 토큰이랑 state 토큰 분리
        const baseTokens = [];
        const stateGroups = {}; // { "default": { hover: token, pressed: token, ... } }

        for (const token of innerTokens) {
          const variant = token.path[3];
          const { base, state } = parseTokenName(variant);

          if (state) {
            if (!stateGroups[base]) stateGroups[base] = {};
            stateGroups[base][state] = token;
          } else {
            baseTokens.push(token);
          }
        }

        // base static let 먼저
        for (const token of baseTokens) {
          const variant = token.path[3];
          const name = toSwiftName(variant);
          const rawValue = token.original?.$value ?? token.original?.value ?? token.$value ?? token.value;
          const baseRef = resolveBaseColorReference(rawValue);
          if (!baseRef) throw new Error(`Cannot resolve base color reference for token "${token.path.join('.')}" (value: ${JSON.stringify(rawValue)})`);
          output += `            public static let ${name} = ${baseRef}\n`;
        }

        // state enum
        for (const [base, states] of Object.entries(stateGroups)) {
          const enumName = capitalize(toSwiftName(base));
          output += `\n            public enum ${enumName} {\n`;
          for (const [state, token] of Object.entries(states)) {
            const rawValue = token.original?.$value ?? token.original?.value ?? token.$value ?? token.value;
            const baseRef = resolveBaseColorReference(rawValue);
            if (!baseRef) throw new Error(`Cannot resolve base color reference for token "${token.path.join('.')}" (value: ${JSON.stringify(rawValue)})`);
            output += `                public static let ${state} = ${baseRef}\n`;
          }
          output += `            }\n`;
        }

        output += `        }\n`;
      }

      output += `    }\n`;
    }

    output += '}\n';
    return output;
  }
});

const sd = new StyleDictionary({
  usesDtcg: true,
  log: { warnings: 'disabled' },
  source: ['tokens/**/*.json'],
  platforms: {
    swift: {
      transforms: [],
      buildPath: 'MDS/Sources/MDS/Foundation/Base/',
      files: [
        {
          destination: 'BaseTypography.swift',
          format: 'ios/swift-typography',
          filter: (token) => token.path[0] === 'typography' && typeof (token.$value ?? token.value) !== 'object'
        },
        {
          destination: 'BaseSpacing.swift',
          format: 'ios/swift-spacing',
          filter: (token) => token.path[0] === 'spacing'
        },
        {
          destination: 'BaseColor.swift',
          format: 'ios/swift-color-base',
          filter: (token) => token.path[0] === 'color' && token.path[1] === 'base'
        }
      ]
    },
    swiftSemantic: {
      transforms: [],
      buildPath: 'MDS/Sources/MDS/Tokens/',
      files: [
        {
          destination: 'Typography.swift',
          format: 'ios/swift-typography-semantic',
          filter: (token) => token.path[0] === 'typography' && typeof (token.$value ?? token.value) === 'object'
        },
        {
          destination: 'SemanticColor.swift',
          format: 'ios/swift-color-semantic',
          filter: (token) => token.path[0] === 'color' && token.path[1] !== 'base'
        }
      ]
    }
  }
});

await sd.buildAllPlatforms();
console.log('Design tokens built successfully.');
