import StyleDictionary from 'style-dictionary';

const capitalize = (str) => str.charAt(0).toUpperCase() + str.slice(1);

const fileHeader = (filename) =>
`//
//  ${filename}
//  MDS
//
//  Auto-generated by Style Dictionary. Do not edit manually.
//

import UIKit

`;

StyleDictionary.registerFormat({
  name: 'ios/swift-typography',
  format: ({ dictionary }) => {
    let output = fileHeader('BaseTypography.swift');
    output += '// MARK: - Base Typography (Internal Only)\n\n';
    output += 'internal enum BaseTypography {\n';

    const groups = {};
    for (const token of dictionary.allTokens) {
      const cat = token.path[1];
      if (!groups[cat]) groups[cat] = [];
      groups[cat].push(token);
    }

    for (const [cat, tokens] of Object.entries(groups)) {
      output += `\n    // MARK: ${capitalize(cat)}\n`;
      output += `    enum ${capitalize(cat)} {\n`;
      for (const token of tokens) {
        const last = token.path[token.path.length - 1];
        let name;
        if (cat === 'size') name = `size${last}`;
        else if (cat === 'lineHeight') name = `lineHeight${last}`;
        else if (last === 'default') name = '`default`';
        else name = last;
        output += `        static let ${name}: CGFloat = ${token.$value ?? token.value}\n`;
      }
      output += `    }\n`;
    }

    output += '}\n';
    return output;
  }
});

StyleDictionary.registerFormat({
  name: 'ios/swift-spacing',
  format: ({ dictionary }) => {
    let output = fileHeader('BaseSpacing.swift');
    output += '// MARK: - Base Spacing (Internal Only)\n\n';
    output += 'internal enum BaseSpacing {\n';

    const groups = {};
    for (const token of dictionary.allTokens) {
      const cat = token.path[1];
      if (!groups[cat]) groups[cat] = [];
      groups[cat].push(token);
    }

    for (const [cat, tokens] of Object.entries(groups)) {
      output += `\n    // MARK: ${capitalize(cat)}\n`;
      output += `    enum ${capitalize(cat)} {\n`;
      for (const token of tokens) {
        const last = token.path[token.path.length - 1];
        output += `        static let size${last}: CGFloat = ${token.$value ?? token.value}\n`;
      }
      output += `    }\n`;
    }

    output += '}\n';
    return output;
  }
});

const sd = new StyleDictionary({
  usesDtcg: true,
  log: { warnings: 'disabled' },
  source: ['tokens/**/*.json'],
  platforms: {
    swift: {
      transforms: [],
      buildPath: 'MDS/Sources/MDS/Foundation/Base/',
      files: [
        {
          destination: 'BaseTypography.swift',
          format: 'ios/swift-typography',
          filter: (token) => token.path[0] === 'typography'
        },
        {
          destination: 'BaseSpacing.swift',
          format: 'ios/swift-spacing',
          filter: (token) => token.path[0] === 'spacing'
        }
      ]
    }
  }
});

await sd.buildAllPlatforms();
console.log('Design tokens built successfully.');
