import StyleDictionary from 'style-dictionary';

const capitalize = (str) => str.charAt(0).toUpperCase() + str.slice(1);

// Strips "px" or "%" units from token values and returns a plain number string.
const toNumber = (val) => parseFloat(String(val).replace('px', '').replace('%', ''));

const fileHeader = (filename) =>
`//
//  ${filename}
//  MDS
//
//  Auto-generated by Style Dictionary. Do not edit manually.
//

import UIKit

`;

StyleDictionary.registerFormat({
  name: 'ios/swift-typography',
  format: ({ dictionary }) => {
    let output = fileHeader('BaseTypography.swift');
    output += '// MARK: - Base Typography (Internal Only)\n\n';
    output += 'internal enum BaseTypography {\n';

    const groups = {};
    for (const token of dictionary.allTokens) {
      const cat = token.path[2];
      if (!groups[cat]) groups[cat] = [];
      groups[cat].push(token);
    }

    for (const [cat, tokens] of Object.entries(groups)) {
      output += `\n    // MARK: ${capitalize(cat)}\n`;
      output += `    enum ${capitalize(cat)} {\n`;
      for (const token of tokens) {
        const last = token.path[token.path.length - 1];
        let name;
        if (cat === 'size' || cat === 'lineHeight') {
          name = last;
        } else if (last === 'default') {
          name = '`default`';
        } else {
          name = last;
        }
        output += `        static let ${name}: CGFloat = ${toNumber(token.$value ?? token.value)}\n`;
      }
      output += `    }\n`;
    }

    output += '}\n';
    return output;
  }
});

StyleDictionary.registerFormat({
  name: 'ios/swift-spacing',
  format: ({ dictionary }) => {
    let output = fileHeader('BaseSpacing.swift');
    output += '// MARK: - Base Spacing (Internal Only)\n\n';
    output += 'internal enum BaseSpacing {\n';

    const groups = {};
    for (const token of dictionary.allTokens) {
      const cat = token.path[1];
      if (!groups[cat]) groups[cat] = [];
      groups[cat].push(token);
    }

    for (const [cat, tokens] of Object.entries(groups)) {
      output += `\n    // MARK: ${capitalize(cat)}\n`;
      output += `    enum ${capitalize(cat)} {\n`;
      for (const token of tokens) {
        const last = token.path[token.path.length - 1];
        output += `        static let ${last}: CGFloat = ${toNumber(token.$value ?? token.value)}\n`;
      }
      output += `    }\n`;
    }

    output += '}\n';
    return output;
  }
});

const fontNameMap = {
  '700': 'Pretendard-Bold',
  '600': 'Pretendard-SemiBold',
  '400': 'Pretendard-Regular',
};

const swiftWeightMap = {
  '700': '.bold',
  '600': '.semibold',
  '400': '.regular',
};

StyleDictionary.registerFormat({
  name: 'ios/swift-typography-semantic',
  format: ({ dictionary }) => {
    let output = fileHeader('Typography.swift');
    output += '// MARK: - Semantic Typography\n\n';
    output += 'public enum Typography {\n';

    for (const token of dictionary.allTokens) {
      const cat = token.path[1];
      const num = token.path[2];
      const name = `${cat}${num}`;
      const val = token.$value ?? token.value;

      const weightKey = String(toNumber(val.fontWeight));
      const fontSize = toNumber(val.fontSize);
      const lineHeight = toNumber(val.lineHeight);
      const letterSpacingPercent = toNumber(val.letterSpacing);
      const letterSpacing = parseFloat((fontSize * (letterSpacingPercent / 100)).toFixed(2));

      const fontName = fontNameMap[weightKey] ?? 'Pretendard-Regular';
      const swiftWeight = swiftWeightMap[weightKey] ?? '.regular';

      output += `    public static let ${name} = MDSFont(\n`;
      output += `        font: UIFont(name: "${fontName}", size: ${fontSize}) ?? .systemFont(ofSize: ${fontSize}, weight: ${swiftWeight}),\n`;
      output += `        lineHeight: ${lineHeight},\n`;
      output += `        letterSpacing: ${letterSpacing}\n`;
      output += `    )\n`;
    }

    output += '}\n';
    return output;
  }
});

const sd = new StyleDictionary({
  usesDtcg: true,
  log: { warnings: 'disabled' },
  source: ['tokens/**/*.json'],
  platforms: {
    swift: {
      transforms: [],
      buildPath: 'MDS/Sources/MDS/Foundation/Base/',
      files: [
        {
          destination: 'BaseTypography.swift',
          format: 'ios/swift-typography',
          filter: (token) => token.path[0] === 'typography' && typeof (token.$value ?? token.value) !== 'object'
        },
        {
          destination: 'BaseSpacing.swift',
          format: 'ios/swift-spacing',
          filter: (token) => token.path[0] === 'spacing'
        }
      ]
    },
    swiftSemantic: {
      transforms: [],
      buildPath: 'MDS/Sources/MDS/Tokens/',
      files: [
        {
          destination: 'Typography.swift',
          format: 'ios/swift-typography-semantic',
          filter: (token) => token.path[0] === 'typography' && typeof (token.$value ?? token.value) === 'object'
        }
      ]
    }
  }
});

await sd.buildAllPlatforms();
console.log('Design tokens built successfully.');
