//
//  BaseSpacing.swift
//  MDS
//
//  Auto-generated by Style Dictionary. Do not edit manually.
//

import UIKit

// MARK: - Base Spacing

public enum BaseSpacing {

    // MARK: Base
    public enum Base {
        public static let s0: CGFloat = 0
        public static let s2: CGFloat = 2
        public static let s4: CGFloat = 4
        public static let s6: CGFloat = 6
        public static let s8: CGFloat = 8
        public static let s10: CGFloat = 10
        public static let s12: CGFloat = 12
        public static let s14: CGFloat = 14
        public static let s16: CGFloat = 16
        public static let s20: CGFloat = 20
        public static let s24: CGFloat = 24
        public static let s28: CGFloat = 28
        public static let s32: CGFloat = 32
        public static let s36: CGFloat = 36
        public static let s40: CGFloat = 40
        public static let s48: CGFloat = 48
        public static let s64: CGFloat = 64
        public static let s72: CGFloat = 72
        public static let s80: CGFloat = 80
        public static let s120: CGFloat = 120
        public static let s160: CGFloat = 160
    }
}
