//
//  BaseRadius.swift
//  MDS
//
//  Auto-generated by Style Dictionary. Do not edit manually.
//

import UIKit

// MARK: - Base Radius

public enum BaseRadius {

    // MARK: Base
    public enum Base {
        public static let r0: CGFloat = 0
        public static let r2: CGFloat = 2
        public static let r4: CGFloat = 4
        public static let r6: CGFloat = 6
        public static let r8: CGFloat = 8
        public static let r10: CGFloat = 10
        public static let r12: CGFloat = 12
        public static let r14: CGFloat = 14
        public static let r16: CGFloat = 16
        public static let r20: CGFloat = 20
        public static let r24: CGFloat = 24
        public static let r32: CGFloat = 32
        public static let full: CGFloat = 9999
    }
}
