//
//  BaseColor.swift
//  MDS
//
//  Auto-generated by Style Dictionary. Do not edit manually.
//

import UIKit

// MARK: - Base Color (Internal Only)

internal extension UIColor {

    // Gray
    static var gray0: UIColor { UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1.0) }
    static var gray10: UIColor { UIColor(red: 0.988, green: 0.988, blue: 0.988, alpha: 1.0) }
    static var gray20: UIColor { UIColor(red: 0.965, green: 0.965, blue: 0.965, alpha: 1.0) }
    static var gray30: UIColor { UIColor(red: 0.941, green: 0.941, blue: 0.941, alpha: 1.0) }
    static var gray50: UIColor { UIColor(red: 0.894, green: 0.894, blue: 0.898, alpha: 1.0) }
    static var gray100: UIColor { UIColor(red: 0.765, green: 0.765, blue: 0.776, alpha: 1.0) }
    static var gray200: UIColor { UIColor(red: 0.616, green: 0.616, blue: 0.643, alpha: 1.0) }
    static var gray300: UIColor { UIColor(red: 0.502, green: 0.502, blue: 0.529, alpha: 1.0) }
    static var gray400: UIColor { UIColor(red: 0.400, green: 0.400, blue: 0.427, alpha: 1.0) }
    static var gray500: UIColor { UIColor(red: 0.318, green: 0.318, blue: 0.349, alpha: 1.0) }
    static var gray600: UIColor { UIColor(red: 0.247, green: 0.247, blue: 0.278, alpha: 1.0) }
    static var gray700: UIColor { UIColor(red: 0.180, green: 0.180, blue: 0.208, alpha: 1.0) }
    static var gray800: UIColor { UIColor(red: 0.125, green: 0.125, blue: 0.145, alpha: 1.0) }
    static var gray900: UIColor { UIColor(red: 0.090, green: 0.094, blue: 0.110, alpha: 1.0) }
    static var gray950: UIColor { UIColor(red: 0.059, green: 0.063, blue: 0.071, alpha: 1.0) }
}
