//
//  BaseSpacing.swift
//  MDS
//
//  Auto-generated by Style Dictionary. Do not edit manually.
//

import UIKit

// MARK: - Base Spacing (Internal Only)

internal enum BaseSpacing {

    // MARK: Size
    enum Size {
        static let size0: CGFloat = 0
        static let size2: CGFloat = 2
        static let size4: CGFloat = 4
        static let size6: CGFloat = 6
        static let size8: CGFloat = 8
        static let size10: CGFloat = 10
        static let size12: CGFloat = 12
        static let size14: CGFloat = 14
        static let size16: CGFloat = 16
        static let size20: CGFloat = 20
        static let size24: CGFloat = 24
        static let size28: CGFloat = 28
        static let size32: CGFloat = 32
        static let size36: CGFloat = 36
        static let size40: CGFloat = 40
        static let size48: CGFloat = 48
        static let size64: CGFloat = 64
        static let size72: CGFloat = 72
        static let size80: CGFloat = 80
        static let size120: CGFloat = 120
        static let size160: CGFloat = 160
    }
}
