//
//  BaseColor.swift
//  MDS
//
//  Auto-generated by Style Dictionary. Do not edit manually.
//

import UIKit

// MARK: - Base Color (Internal Only)

internal enum BaseColor {

    // MARK: Gray
    enum Gray {
        static let c0 = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1)
        static let c10 = UIColor(red: 0.988, green: 0.988, blue: 0.988, alpha: 1)
        static let c20 = UIColor(red: 0.965, green: 0.965, blue: 0.965, alpha: 1)
        static let c30 = UIColor(red: 0.941, green: 0.941, blue: 0.941, alpha: 1)
        static let c50 = UIColor(red: 0.894, green: 0.894, blue: 0.898, alpha: 1)
        static let c100 = UIColor(red: 0.765, green: 0.765, blue: 0.776, alpha: 1)
        static let c200 = UIColor(red: 0.616, green: 0.616, blue: 0.643, alpha: 1)
        static let c300 = UIColor(red: 0.502, green: 0.502, blue: 0.529, alpha: 1)
        static let c400 = UIColor(red: 0.400, green: 0.400, blue: 0.427, alpha: 1)
        static let c500 = UIColor(red: 0.318, green: 0.318, blue: 0.349, alpha: 1)
        static let c600 = UIColor(red: 0.247, green: 0.247, blue: 0.278, alpha: 1)
        static let c700 = UIColor(red: 0.180, green: 0.180, blue: 0.208, alpha: 1)
        static let c800 = UIColor(red: 0.125, green: 0.125, blue: 0.145, alpha: 1)
        static let c900 = UIColor(red: 0.090, green: 0.094, blue: 0.110, alpha: 1)
        static let c950 = UIColor(red: 0.059, green: 0.063, blue: 0.071, alpha: 1)
    }

    // MARK: Orange
    enum Orange {
        static let c50 = UIColor(red: 1.000, green: 0.925, blue: 0.898, alpha: 1)
        static let c100 = UIColor(red: 1.000, green: 0.808, blue: 0.741, alpha: 1)
        static let c200 = UIColor(red: 1.000, green: 0.643, blue: 0.502, alpha: 1)
        static let c300 = UIColor(red: 1.000, green: 0.514, blue: 0.290, alpha: 1)
        static let c400 = UIColor(red: 0.969, green: 0.447, blue: 0.204, alpha: 1)
        static let c500 = UIColor(red: 0.831, green: 0.349, blue: 0.110, alpha: 1)
        static let c600 = UIColor(red: 0.678, green: 0.306, blue: 0.090, alpha: 1)
        static let c700 = UIColor(red: 0.522, green: 0.239, blue: 0.067, alpha: 1)
        static let c800 = UIColor(red: 0.361, green: 0.169, blue: 0.047, alpha: 1)
        static let c900 = UIColor(red: 0.259, green: 0.129, blue: 0.035, alpha: 1)
        static let c950 = UIColor(red: 0.173, green: 0.114, blue: 0.094, alpha: 1)
    }

    // MARK: Blue
    enum Blue {
        static let c50 = UIColor(red: 0.784, green: 0.882, blue: 1.000, alpha: 1)
        static let c100 = UIColor(red: 0.561, green: 0.753, blue: 1.000, alpha: 1)
        static let c200 = UIColor(red: 0.380, green: 0.620, blue: 1.000, alpha: 1)
        static let c300 = UIColor(red: 0.267, green: 0.522, blue: 1.000, alpha: 1)
        static let c400 = UIColor(red: 0.204, green: 0.435, blue: 0.980, alpha: 1)
        static let c500 = UIColor(red: 0.173, green: 0.325, blue: 0.875, alpha: 1)
        static let c600 = UIColor(red: 0.149, green: 0.286, blue: 0.702, alpha: 1)
        static let c700 = UIColor(red: 0.145, green: 0.231, blue: 0.549, alpha: 1)
        static let c800 = UIColor(red: 0.137, green: 0.188, blue: 0.416, alpha: 1)
        static let c900 = UIColor(red: 0.125, green: 0.153, blue: 0.302, alpha: 1)
        static let c950 = UIColor(red: 0.071, green: 0.102, blue: 0.169, alpha: 1)
    }

    // MARK: Red
    enum Red {
        static let c50 = UIColor(red: 1.000, green: 0.820, blue: 0.827, alpha: 1)
        static let c100 = UIColor(red: 1.000, green: 0.659, blue: 0.678, alpha: 1)
        static let c200 = UIColor(red: 1.000, green: 0.506, blue: 0.545, alpha: 1)
        static let c300 = UIColor(red: 0.980, green: 0.380, blue: 0.427, alpha: 1)
        static let c400 = UIColor(red: 0.941, green: 0.259, blue: 0.318, alpha: 1)
        static let c500 = UIColor(red: 0.792, green: 0.184, blue: 0.239, alpha: 1)
        static let c600 = UIColor(red: 0.620, green: 0.153, blue: 0.200, alpha: 1)
        static let c700 = UIColor(red: 0.478, green: 0.141, blue: 0.176, alpha: 1)
        static let c800 = UIColor(red: 0.337, green: 0.125, blue: 0.145, alpha: 1)
        static let c900 = UIColor(red: 0.235, green: 0.125, blue: 0.125, alpha: 1)
        static let c950 = UIColor(red: 0.169, green: 0.098, blue: 0.114, alpha: 1)
    }

    // MARK: Green
    enum Green {
        static let c50 = UIColor(red: 0.800, green: 1.000, blue: 0.925, alpha: 1)
        static let c100 = UIColor(red: 0.510, green: 0.965, blue: 0.796, alpha: 1)
        static let c200 = UIColor(red: 0.510, green: 0.965, blue: 0.796, alpha: 1)
        static let c300 = UIColor(red: 0.149, green: 0.812, blue: 0.569, alpha: 1)
        static let c400 = UIColor(red: 0.086, green: 0.749, blue: 0.506, alpha: 1)
        static let c500 = UIColor(red: 0.075, green: 0.627, blue: 0.424, alpha: 1)
        static let c600 = UIColor(red: 0.075, green: 0.541, blue: 0.369, alpha: 1)
        static let c700 = UIColor(red: 0.075, green: 0.427, blue: 0.298, alpha: 1)
        static let c800 = UIColor(red: 0.075, green: 0.325, blue: 0.235, alpha: 1)
        static let c900 = UIColor(red: 0.082, green: 0.216, blue: 0.169, alpha: 1)
        static let c950 = UIColor(red: 0.094, green: 0.161, blue: 0.149, alpha: 1)
    }

    // MARK: Yellow
    enum Yellow {
        static let c50 = UIColor(red: 1.000, green: 0.957, blue: 0.831, alpha: 1)
        static let c100 = UIColor(red: 1.000, green: 0.914, blue: 0.698, alpha: 1)
        static let c200 = UIColor(red: 1.000, green: 0.871, blue: 0.541, alpha: 1)
        static let c300 = UIColor(red: 1.000, green: 0.804, blue: 0.349, alpha: 1)
        static let c400 = UIColor(red: 1.000, green: 0.761, blue: 0.204, alpha: 1)
        static let c500 = UIColor(red: 1.000, green: 0.702, blue: 0.149, alpha: 1)
        static let c600 = UIColor(red: 0.922, green: 0.627, blue: 0.118, alpha: 1)
        static let c700 = UIColor(red: 0.710, green: 0.482, blue: 0.114, alpha: 1)
        static let c800 = UIColor(red: 0.447, green: 0.325, blue: 0.118, alpha: 1)
        static let c900 = UIColor(red: 0.325, green: 0.255, blue: 0.137, alpha: 1)
        static let c950 = UIColor(red: 0.192, green: 0.165, blue: 0.118, alpha: 1)
    }
}
