//
//  BaseTypography.swift
//  MDS
//
//  Auto-generated by Style Dictionary. Do not edit manually.
//

import UIKit

// MARK: - Base Typography (Internal Only)

internal enum BaseTypography {

    // MARK: Weight
    enum Weight {
        static let bold: CGFloat = 700
        static let semibold: CGFloat = 600
        static let regular: CGFloat = 400
    }

    // MARK: Size
    enum Size {
        static let size12: CGFloat = 13
        static let size14: CGFloat = 14
        static let size16: CGFloat = 16
        static let size18: CGFloat = 18
        static let size20: CGFloat = 20
        static let size24: CGFloat = 24
        static let size32: CGFloat = 32
        static let size36: CGFloat = 36
    }

    // MARK: LineHeight
    enum LineHeight {
        static let lineHeight16: CGFloat = 16
        static let lineHeight18: CGFloat = 18
        static let lineHeight22: CGFloat = 22
        static let lineHeight24: CGFloat = 24
        static let lineHeight26: CGFloat = 26
        static let lineHeight30: CGFloat = 30
        static let lineHeight36: CGFloat = 36
        static let lineHeight42: CGFloat = 42
        static let lineHeight48: CGFloat = 48
    }

    // MARK: LetterSpacing
    enum LetterSpacing {
        static let wide: CGFloat = -1.5
        static let `default`: CGFloat = -2
    }
}
