//
//  BaseColorCatalogData.swift
//  MDS
//
//  Auto-generated by Style Dictionary. Do not edit manually.
//

import UIKit

// MARK: - Base Color Catalog Data

@_spi(MDSCatalog) public struct BaseColorCatalogEntry: @unchecked Sendable {
    public let name: String
    public let color: UIColor
}

@_spi(MDSCatalog) public enum BaseColorCatalogData {
    public static let gray: [BaseColorCatalogEntry] = [
        .init(name: "gray.0", color: BaseColor.gray0),
        .init(name: "gray.10", color: BaseColor.gray10),
        .init(name: "gray.20", color: BaseColor.gray20),
        .init(name: "gray.30", color: BaseColor.gray30),
        .init(name: "gray.50", color: BaseColor.gray50),
        .init(name: "gray.100", color: BaseColor.gray100),
        .init(name: "gray.200", color: BaseColor.gray200),
        .init(name: "gray.300", color: BaseColor.gray300),
        .init(name: "gray.400", color: BaseColor.gray400),
        .init(name: "gray.500", color: BaseColor.gray500),
        .init(name: "gray.600", color: BaseColor.gray600),
        .init(name: "gray.700", color: BaseColor.gray700),
        .init(name: "gray.800", color: BaseColor.gray800),
        .init(name: "gray.900", color: BaseColor.gray900),
        .init(name: "gray.950", color: BaseColor.gray950),
    ]
    public static let orange: [BaseColorCatalogEntry] = [
        .init(name: "orange.50", color: BaseColor.orange50),
        .init(name: "orange.100", color: BaseColor.orange100),
        .init(name: "orange.200", color: BaseColor.orange200),
        .init(name: "orange.300", color: BaseColor.orange300),
        .init(name: "orange.400", color: BaseColor.orange400),
        .init(name: "orange.500", color: BaseColor.orange500),
        .init(name: "orange.600", color: BaseColor.orange600),
        .init(name: "orange.700", color: BaseColor.orange700),
        .init(name: "orange.800", color: BaseColor.orange800),
        .init(name: "orange.900", color: BaseColor.orange900),
        .init(name: "orange.950", color: BaseColor.orange950),
    ]
    public static let blue: [BaseColorCatalogEntry] = [
        .init(name: "blue.50", color: BaseColor.blue50),
        .init(name: "blue.100", color: BaseColor.blue100),
        .init(name: "blue.200", color: BaseColor.blue200),
        .init(name: "blue.300", color: BaseColor.blue300),
        .init(name: "blue.400", color: BaseColor.blue400),
        .init(name: "blue.500", color: BaseColor.blue500),
        .init(name: "blue.600", color: BaseColor.blue600),
        .init(name: "blue.700", color: BaseColor.blue700),
        .init(name: "blue.800", color: BaseColor.blue800),
        .init(name: "blue.900", color: BaseColor.blue900),
        .init(name: "blue.950", color: BaseColor.blue950),
    ]
    public static let red: [BaseColorCatalogEntry] = [
        .init(name: "red.50", color: BaseColor.red50),
        .init(name: "red.100", color: BaseColor.red100),
        .init(name: "red.200", color: BaseColor.red200),
        .init(name: "red.300", color: BaseColor.red300),
        .init(name: "red.400", color: BaseColor.red400),
        .init(name: "red.500", color: BaseColor.red500),
        .init(name: "red.600", color: BaseColor.red600),
        .init(name: "red.700", color: BaseColor.red700),
        .init(name: "red.800", color: BaseColor.red800),
        .init(name: "red.900", color: BaseColor.red900),
        .init(name: "red.950", color: BaseColor.red950),
    ]
    public static let green: [BaseColorCatalogEntry] = [
        .init(name: "green.50", color: BaseColor.green50),
        .init(name: "green.100", color: BaseColor.green100),
        .init(name: "green.200", color: BaseColor.green200),
        .init(name: "green.300", color: BaseColor.green300),
        .init(name: "green.400", color: BaseColor.green400),
        .init(name: "green.500", color: BaseColor.green500),
        .init(name: "green.600", color: BaseColor.green600),
        .init(name: "green.700", color: BaseColor.green700),
        .init(name: "green.800", color: BaseColor.green800),
        .init(name: "green.900", color: BaseColor.green900),
        .init(name: "green.950", color: BaseColor.green950),
    ]
    public static let yellow: [BaseColorCatalogEntry] = [
        .init(name: "yellow.50", color: BaseColor.yellow50),
        .init(name: "yellow.100", color: BaseColor.yellow100),
        .init(name: "yellow.200", color: BaseColor.yellow200),
        .init(name: "yellow.300", color: BaseColor.yellow300),
        .init(name: "yellow.400", color: BaseColor.yellow400),
        .init(name: "yellow.500", color: BaseColor.yellow500),
        .init(name: "yellow.600", color: BaseColor.yellow600),
        .init(name: "yellow.700", color: BaseColor.yellow700),
        .init(name: "yellow.800", color: BaseColor.yellow800),
        .init(name: "yellow.900", color: BaseColor.yellow900),
        .init(name: "yellow.950", color: BaseColor.yellow950),
    ]

    public static let groups: [(paletteName: String, entries: [BaseColorCatalogEntry])] = [
        ("Gray", gray),
        ("Orange", orange),
        ("Blue", blue),
        ("Red", red),
        ("Green", green),
        ("Yellow", yellow),
    ]
}
