//
//  BaseTypographyCatalogData.swift
//  MDS
//
//  Auto-generated by Style Dictionary. Do not edit manually.
//

import UIKit

// MARK: - Base Typography Catalog Data

@_spi(MDSCatalog) public struct BaseTypographyCatalogEntry {
    public let name: String
    public let value: CGFloat
}

@_spi(MDSCatalog) public enum BaseTypographyCatalogData {
    public static let weight: [BaseTypographyCatalogEntry] = [
        .init(name: "bold", value: BaseTypography.Weight.bold),
        .init(name: "semibold", value: BaseTypography.Weight.semibold),
        .init(name: "regular", value: BaseTypography.Weight.regular),
    ]
    public static let size: [BaseTypographyCatalogEntry] = [
        .init(name: "t12", value: BaseTypography.Size.t12),
        .init(name: "t14", value: BaseTypography.Size.t14),
        .init(name: "t16", value: BaseTypography.Size.t16),
        .init(name: "t18", value: BaseTypography.Size.t18),
        .init(name: "t20", value: BaseTypography.Size.t20),
        .init(name: "t24", value: BaseTypography.Size.t24),
        .init(name: "t28", value: BaseTypography.Size.t28),
        .init(name: "t32", value: BaseTypography.Size.t32),
    ]
    public static let lineHeight: [BaseTypographyCatalogEntry] = [
        .init(name: "t16", value: BaseTypography.LineHeight.t16),
        .init(name: "t18", value: BaseTypography.LineHeight.t18),
        .init(name: "t22", value: BaseTypography.LineHeight.t22),
        .init(name: "t24", value: BaseTypography.LineHeight.t24),
        .init(name: "t26", value: BaseTypography.LineHeight.t26),
        .init(name: "t30", value: BaseTypography.LineHeight.t30),
        .init(name: "t36", value: BaseTypography.LineHeight.t36),
        .init(name: "t42", value: BaseTypography.LineHeight.t42),
        .init(name: "t48", value: BaseTypography.LineHeight.t48),
    ]
    public static let letterSpacing: [BaseTypographyCatalogEntry] = [
        .init(name: "wide", value: BaseTypography.LetterSpacing.wide),
        .init(name: "default", value: BaseTypography.LetterSpacing.`default`),
    ]

    public static let groups: [(categoryName: String, entries: [BaseTypographyCatalogEntry])] = [
        ("weight", weight),
        ("size", size),
        ("lineHeight", lineHeight),
        ("letterSpacing", letterSpacing),
    ]
}
