//
//  SemanticColor.swift
//  MDS
//
//  Auto-generated by Style Dictionary. Do not edit manually.
//

import UIKit

// MARK: - Semantic Color

public enum SemanticColor {

    public enum Bg {

        public enum Neutral {
            public static let inverse = BaseColor.gray10
            public static let inverseHover = BaseColor.gray100
            public static let inversePressed = BaseColor.gray100
            public static let bold = BaseColor.gray500
            public static let boldDisabled = BaseColor.gray700
            public static let `default` = BaseColor.gray600
            public static let defaultHover = BaseColor.gray500
            public static let defaultPressed = BaseColor.gray500
            public static let defaultDisabled = BaseColor.gray800
            public static let subtle = BaseColor.gray700
            public static let subtleHover = BaseColor.gray600
            public static let subtlePressed = BaseColor.gray600
            public static let ghost = BaseColor.gray800
            public static let ghostHover = BaseColor.gray700
            public static let ghostPressed = BaseColor.gray700
        }

        public enum Brand {
            public static let `default` = BaseColor.orange400
            public static let subtle = BaseColor.orange700
            public static let ghost = BaseColor.orange950
        }

        public enum Secondary {
            public static let `default` = BaseColor.blue400
            public static let defaultHover = BaseColor.blue500
            public static let defaultPressed = BaseColor.blue600
            public static let subtle = BaseColor.blue900
            public static let ghost = BaseColor.blue950
        }

        public enum Information {
            public static let ghost = BaseColor.blue950
        }

        public enum Success {
            public static let ghost = BaseColor.green950
        }

        public enum Danger {
            public static let `default` = BaseColor.red400
            public static let defaultHover = BaseColor.red500
            public static let defaultPressed = BaseColor.red600
            public static let ghost = BaseColor.red950
        }

        public enum Dim {
            public static let `default` = BaseColor.gray950
        }
    }

    public enum Fg {

        public enum Neutral {
            public static let bold = BaseColor.gray10
            public static let `default` = BaseColor.gray100
            public static let defaultDisabled = BaseColor.gray500
            public static let subtle = BaseColor.gray300
            public static let ghost = BaseColor.gray500
            public static let inverse = BaseColor.gray950
        }

        public enum Brand {
            public static let `default` = BaseColor.orange400
        }

        public enum Secondary {
            public static let `default` = BaseColor.blue400
        }

        public enum Success {
            public static let bold = BaseColor.green100
            public static let `default` = BaseColor.green400
            public static let subtle = BaseColor.green600
        }

        public enum Danger {
            public static let bold = BaseColor.red100
            public static let `default` = BaseColor.red400
            public static let subtle = BaseColor.red600
        }

        public enum Attention {
            public static let bold = BaseColor.yellow200
            public static let `default` = BaseColor.yellow400
            public static let subtle = BaseColor.yellow600
        }

        public enum Information {
            public static let `default` = BaseColor.blue400
            public static let subtle = BaseColor.blue600
        }
    }

    public enum Stroke {

        public enum Neutral {
            public static let `default` = BaseColor.gray600
            public static let defaultFocused = BaseColor.gray200
            public static let defaultDisabled = BaseColor.gray700
            public static let inverse = BaseColor.gray10
            public static let subtle = BaseColor.gray700
            public static let ghost = BaseColor.gray800
        }

        public enum Brand {
            public static let `default` = BaseColor.orange400
            public static let subtle = BaseColor.orange600
        }

        public enum Secondary {
            public static let `default` = BaseColor.blue400
            public static let subtle = BaseColor.blue600
        }

        public enum Information {
            public static let subtle = BaseColor.blue600
        }

        public enum Danger {
            public static let `default` = BaseColor.red400
        }
    }
}
