//
//  Typography.swift
//  MDS
//
//  Auto-generated by Style Dictionary. Do not edit manually.
//

import UIKit

// MARK: - Semantic Typography

public enum Typography {
    public static let heading1 = MDSFont(
        font: UIFont(name: "Pretendard-Bold", size: 32) ?? .systemFont(ofSize: 32, weight: .bold),
        lineHeight: 48,
        letterSpacing: -0.64
    )
    public static let heading2 = MDSFont(
        font: UIFont(name: "Pretendard-Bold", size: 24) ?? .systemFont(ofSize: 24, weight: .bold),
        lineHeight: 36,
        letterSpacing: -0.48
    )
    public static let heading3 = MDSFont(
        font: UIFont(name: "Pretendard-Bold", size: 20) ?? .systemFont(ofSize: 20, weight: .bold),
        lineHeight: 30,
        letterSpacing: -0.4
    )
    public static let heading4 = MDSFont(
        font: UIFont(name: "Pretendard-Bold", size: 16) ?? .systemFont(ofSize: 16, weight: .bold),
        lineHeight: 24,
        letterSpacing: -0.24
    )
    public static let title1 = MDSFont(
        font: UIFont(name: "Pretendard-SemiBold", size: 28) ?? .systemFont(ofSize: 28, weight: .semibold),
        lineHeight: 42,
        letterSpacing: -0.56
    )
    public static let title2 = MDSFont(
        font: UIFont(name: "Pretendard-SemiBold", size: 24) ?? .systemFont(ofSize: 24, weight: .semibold),
        lineHeight: 36,
        letterSpacing: -0.48
    )
    public static let title3 = MDSFont(
        font: UIFont(name: "Pretendard-SemiBold", size: 20) ?? .systemFont(ofSize: 20, weight: .semibold),
        lineHeight: 30,
        letterSpacing: -0.4
    )
    public static let title4 = MDSFont(
        font: UIFont(name: "Pretendard-SemiBold", size: 16) ?? .systemFont(ofSize: 16, weight: .semibold),
        lineHeight: 24,
        letterSpacing: -0.24
    )
    public static let body1 = MDSFont(
        font: UIFont(name: "Pretendard-Regular", size: 16) ?? .systemFont(ofSize: 16, weight: .regular),
        lineHeight: 26,
        letterSpacing: -0.24
    )
    public static let body2 = MDSFont(
        font: UIFont(name: "Pretendard-Regular", size: 14) ?? .systemFont(ofSize: 14, weight: .regular),
        lineHeight: 22,
        letterSpacing: -0.21
    )
    public static let label1 = MDSFont(
        font: UIFont(name: "Pretendard-SemiBold", size: 18) ?? .systemFont(ofSize: 18, weight: .semibold),
        lineHeight: 24,
        letterSpacing: -0.36
    )
    public static let label2 = MDSFont(
        font: UIFont(name: "Pretendard-SemiBold", size: 16) ?? .systemFont(ofSize: 16, weight: .semibold),
        lineHeight: 22,
        letterSpacing: -0.32
    )
    public static let label3 = MDSFont(
        font: UIFont(name: "Pretendard-SemiBold", size: 14) ?? .systemFont(ofSize: 14, weight: .semibold),
        lineHeight: 18,
        letterSpacing: -0.28
    )
    public static let label4 = MDSFont(
        font: UIFont(name: "Pretendard-SemiBold", size: 12) ?? .systemFont(ofSize: 12, weight: .semibold),
        lineHeight: 16,
        letterSpacing: -0.24
    )
}
