//
//  ColorTokenDataSource.swift
//  MDSStoryBook
//
//  Auto-generated by Style Dictionary. Do not edit manually.
//

import MDS

enum ColorTokenDataSource {
    static let sections: [ColorTokenSection] = [
        ColorTokenSection(title: "Bg / Neutral", items: [
            ColorTokenItem(name: "inverse", color: SemanticColor.Bg.Neutral.inverse, baseTokenPath: "color.base.gray.10"),
            ColorTokenItem(name: "bold", color: SemanticColor.Bg.Neutral.bold, baseTokenPath: "color.base.gray.500"),
            ColorTokenItem(name: "default", color: SemanticColor.Bg.Neutral.`default`, baseTokenPath: "color.base.gray.600"),
            ColorTokenItem(name: "subtle", color: SemanticColor.Bg.Neutral.subtle, baseTokenPath: "color.base.gray.700"),
            ColorTokenItem(name: "ghost", color: SemanticColor.Bg.Neutral.ghost, baseTokenPath: "color.base.gray.800"),
            ColorTokenItem(name: "inverse · hover", color: SemanticColor.Bg.Neutral.Inverse.hover, baseTokenPath: "color.base.gray.100"),
            ColorTokenItem(name: "inverse · pressed", color: SemanticColor.Bg.Neutral.Inverse.pressed, baseTokenPath: "color.base.gray.100"),
            ColorTokenItem(name: "bold · disabled", color: SemanticColor.Bg.Neutral.Bold.disabled, baseTokenPath: "color.base.gray.700"),
            ColorTokenItem(name: "default · hover", color: SemanticColor.Bg.Neutral.Default.hover, baseTokenPath: "color.base.gray.500"),
            ColorTokenItem(name: "default · pressed", color: SemanticColor.Bg.Neutral.Default.pressed, baseTokenPath: "color.base.gray.500"),
            ColorTokenItem(name: "default · disabled", color: SemanticColor.Bg.Neutral.Default.disabled, baseTokenPath: "color.base.gray.800"),
            ColorTokenItem(name: "subtle · hover", color: SemanticColor.Bg.Neutral.Subtle.hover, baseTokenPath: "color.base.gray.600"),
            ColorTokenItem(name: "subtle · pressed", color: SemanticColor.Bg.Neutral.Subtle.pressed, baseTokenPath: "color.base.gray.600"),
            ColorTokenItem(name: "ghost · hover", color: SemanticColor.Bg.Neutral.Ghost.hover, baseTokenPath: "color.base.gray.700"),
            ColorTokenItem(name: "ghost · pressed", color: SemanticColor.Bg.Neutral.Ghost.pressed, baseTokenPath: "color.base.gray.700"),
        ]),
        ColorTokenSection(title: "Bg / Brand", items: [
            ColorTokenItem(name: "default", color: SemanticColor.Bg.Brand.`default`, baseTokenPath: "color.base.orange.400"),
            ColorTokenItem(name: "subtle", color: SemanticColor.Bg.Brand.subtle, baseTokenPath: "color.base.orange.700"),
            ColorTokenItem(name: "ghost", color: SemanticColor.Bg.Brand.ghost, baseTokenPath: "color.base.orange.950"),
        ]),
        ColorTokenSection(title: "Bg / Secondary", items: [
            ColorTokenItem(name: "default", color: SemanticColor.Bg.Secondary.`default`, baseTokenPath: "color.base.blue.400"),
            ColorTokenItem(name: "subtle", color: SemanticColor.Bg.Secondary.subtle, baseTokenPath: "color.base.blue.900"),
            ColorTokenItem(name: "ghost", color: SemanticColor.Bg.Secondary.ghost, baseTokenPath: "color.base.blue.950"),
            ColorTokenItem(name: "default · hover", color: SemanticColor.Bg.Secondary.Default.hover, baseTokenPath: "color.base.blue.500"),
            ColorTokenItem(name: "default · pressed", color: SemanticColor.Bg.Secondary.Default.pressed, baseTokenPath: "color.base.blue.600"),
        ]),
        ColorTokenSection(title: "Bg / Information", items: [
            ColorTokenItem(name: "ghost", color: SemanticColor.Bg.Information.ghost, baseTokenPath: "color.base.blue.950"),
        ]),
        ColorTokenSection(title: "Bg / Success", items: [
            ColorTokenItem(name: "ghost", color: SemanticColor.Bg.Success.ghost, baseTokenPath: "color.base.green.950"),
        ]),
        ColorTokenSection(title: "Bg / Danger", items: [
            ColorTokenItem(name: "default", color: SemanticColor.Bg.Danger.`default`, baseTokenPath: "color.base.red.400"),
            ColorTokenItem(name: "ghost", color: SemanticColor.Bg.Danger.ghost, baseTokenPath: "color.base.red.950"),
            ColorTokenItem(name: "default · hover", color: SemanticColor.Bg.Danger.Default.hover, baseTokenPath: "color.base.red.500"),
            ColorTokenItem(name: "default · pressed", color: SemanticColor.Bg.Danger.Default.pressed, baseTokenPath: "color.base.red.600"),
        ]),
        ColorTokenSection(title: "Bg / Dim", items: [
            ColorTokenItem(name: "default", color: SemanticColor.Bg.Dim.`default`, baseTokenPath: "color.base.gray.950"),
        ]),
        ColorTokenSection(title: "Bg / Layer", items: [
            ColorTokenItem(name: "basement", color: SemanticColor.Bg.Layer.basement, baseTokenPath: "color.base.gray.950"),
            ColorTokenItem(name: "default", color: SemanticColor.Bg.Layer.`default`, baseTokenPath: "color.base.gray.900"),
            ColorTokenItem(name: "basement · hover", color: SemanticColor.Bg.Layer.Basement.hover, baseTokenPath: "color.base.gray.800"),
            ColorTokenItem(name: "default · hover", color: SemanticColor.Bg.Layer.Default.hover, baseTokenPath: "color.base.gray.800"),
        ]),
        ColorTokenSection(title: "Fg / Neutral", items: [
            ColorTokenItem(name: "bold", color: SemanticColor.Fg.Neutral.bold, baseTokenPath: "color.base.gray.10"),
            ColorTokenItem(name: "default", color: SemanticColor.Fg.Neutral.`default`, baseTokenPath: "color.base.gray.100"),
            ColorTokenItem(name: "subtle", color: SemanticColor.Fg.Neutral.subtle, baseTokenPath: "color.base.gray.300"),
            ColorTokenItem(name: "ghost", color: SemanticColor.Fg.Neutral.ghost, baseTokenPath: "color.base.gray.500"),
            ColorTokenItem(name: "inverse", color: SemanticColor.Fg.Neutral.inverse, baseTokenPath: "color.base.gray.950"),
            ColorTokenItem(name: "default · disabled", color: SemanticColor.Fg.Neutral.Default.disabled, baseTokenPath: "color.base.gray.500"),
            ColorTokenItem(name: "ghost · disabled", color: SemanticColor.Fg.Neutral.Ghost.disabled, baseTokenPath: "color.base.gray.700"),
        ]),
        ColorTokenSection(title: "Fg / Brand", items: [
            ColorTokenItem(name: "default", color: SemanticColor.Fg.Brand.`default`, baseTokenPath: "color.base.orange.400"),
        ]),
        ColorTokenSection(title: "Fg / Secondary", items: [
            ColorTokenItem(name: "default", color: SemanticColor.Fg.Secondary.`default`, baseTokenPath: "color.base.blue.400"),
        ]),
        ColorTokenSection(title: "Fg / Information", items: [
            ColorTokenItem(name: "default", color: SemanticColor.Fg.Information.`default`, baseTokenPath: "color.base.blue.400"),
            ColorTokenItem(name: "subtle", color: SemanticColor.Fg.Information.subtle, baseTokenPath: "color.base.blue.600"),
        ]),
        ColorTokenSection(title: "Fg / Success", items: [
            ColorTokenItem(name: "bold", color: SemanticColor.Fg.Success.bold, baseTokenPath: "color.base.green.100"),
            ColorTokenItem(name: "default", color: SemanticColor.Fg.Success.`default`, baseTokenPath: "color.base.green.400"),
            ColorTokenItem(name: "subtle", color: SemanticColor.Fg.Success.subtle, baseTokenPath: "color.base.green.600"),
        ]),
        ColorTokenSection(title: "Fg / Danger", items: [
            ColorTokenItem(name: "bold", color: SemanticColor.Fg.Danger.bold, baseTokenPath: "color.base.red.100"),
            ColorTokenItem(name: "default", color: SemanticColor.Fg.Danger.`default`, baseTokenPath: "color.base.red.400"),
            ColorTokenItem(name: "subtle", color: SemanticColor.Fg.Danger.subtle, baseTokenPath: "color.base.red.600"),
        ]),
        ColorTokenSection(title: "Fg / Attention", items: [
            ColorTokenItem(name: "bold", color: SemanticColor.Fg.Attention.bold, baseTokenPath: "color.base.yellow.200"),
            ColorTokenItem(name: "default", color: SemanticColor.Fg.Attention.`default`, baseTokenPath: "color.base.yellow.400"),
            ColorTokenItem(name: "subtle", color: SemanticColor.Fg.Attention.subtle, baseTokenPath: "color.base.yellow.600"),
        ]),
        ColorTokenSection(title: "Stroke / Neutral", items: [
            ColorTokenItem(name: "default", color: SemanticColor.Stroke.Neutral.`default`, baseTokenPath: "color.base.gray.600"),
            ColorTokenItem(name: "inverse", color: SemanticColor.Stroke.Neutral.inverse, baseTokenPath: "color.base.gray.10"),
            ColorTokenItem(name: "subtle", color: SemanticColor.Stroke.Neutral.subtle, baseTokenPath: "color.base.gray.700"),
            ColorTokenItem(name: "ghost", color: SemanticColor.Stroke.Neutral.ghost, baseTokenPath: "color.base.gray.800"),
            ColorTokenItem(name: "default · focused", color: SemanticColor.Stroke.Neutral.Default.focused, baseTokenPath: "color.base.gray.200"),
            ColorTokenItem(name: "default · disabled", color: SemanticColor.Stroke.Neutral.Default.disabled, baseTokenPath: "color.base.gray.700"),
        ]),
        ColorTokenSection(title: "Stroke / Brand", items: [
            ColorTokenItem(name: "default", color: SemanticColor.Stroke.Brand.`default`, baseTokenPath: "color.base.orange.400"),
            ColorTokenItem(name: "subtle", color: SemanticColor.Stroke.Brand.subtle, baseTokenPath: "color.base.orange.600"),
        ]),
        ColorTokenSection(title: "Stroke / Secondary", items: [
            ColorTokenItem(name: "default", color: SemanticColor.Stroke.Secondary.`default`, baseTokenPath: "color.base.blue.400"),
            ColorTokenItem(name: "subtle", color: SemanticColor.Stroke.Secondary.subtle, baseTokenPath: "color.base.blue.600"),
        ]),
        ColorTokenSection(title: "Stroke / Information", items: [
            ColorTokenItem(name: "subtle", color: SemanticColor.Stroke.Information.subtle, baseTokenPath: "color.base.blue.600"),
        ]),
        ColorTokenSection(title: "Stroke / Danger", items: [
            ColorTokenItem(name: "default", color: SemanticColor.Stroke.Danger.`default`, baseTokenPath: "color.base.red.400"),
        ]),
    ]
}
